FROM minio/mc:latest AS mc-bin

FROM alpine:3.20

RUN apk add --no-cache postgresql16-client tzdata bash curl
COPY --from=mc-bin /usr/bin/mc /usr/local/bin/mc

WORKDIR /app
COPY scripts/ ./scripts/

RUN apk add --no-cache dos2unix && dos2unix ./scripts/*.sh && chmod +x ./scripts/*.sh

ENTRYPOINT ["/app/scripts/backup-cron-entrypoint.sh"]