DROP TABLE IF EXISTS lures CASCADE;
DROP TABLE IF EXISTS lure_types CASCADE;
DROP TABLE IF EXISTS rod_specs CASCADE;
DROP TABLE IF EXISTS gear_items CASCADE;
DROP TABLE IF EXISTS gear_categories CASCADE;
DROP TABLE IF EXISTS gear_manufacturers CASCADE;