DROP TABLE IF EXISTS seasonal_bans CASCADE;
DROP TABLE IF EXISTS mixture_components CASCADE;
DROP TABLE IF EXISTS groundbait_mixtures CASCADE;
DROP TABLE IF EXISTS baits CASCADE;
DROP TABLE IF EXISTS weather_observations CASCADE;
DROP TABLE IF EXISTS weather_types CASCADE;
DROP TABLE IF EXISTS catch_photos CASCADE;
DROP TABLE IF EXISTS catches CASCADE;